services:
  sysbench:
    build:
      context: ../
      dockerfile: base/sysbench-dockerfile
    platform: linux/amd64
    image: ytooyama/yugabyte-dev-sysbench:latest
    tty: true
    volumes:
      - sysbench-vol:/root/data/
    networks:
      - yugaplus-network

  yugabyte1:
    build:
      context: ../
      dockerfile: base/base-dockerfile
    image: ytooyama/yugabyte-dev-tc:latest
    command: sh -c "bin/yugabyted start --advertise_address=yugabyte1 --background=false"
    ports:
      - "15433:15433"
      - "5433:5433"
    volumes:
      - yugabyte1-vol:/root/var/
    networks:
      - yugaplus-network
    cap_add:
      - NET_ADMIN

  yugabyte2:
    image: ytooyama/yugabyte-dev-tc:latest
    command: sh -c "sleep 12 && bin/yugabyted start --advertise_address=yugabyte2 --background=false --join=yugabyte1"
    ports:
      - "5434:5433"
    volumes:
      - yugabyte2-vol:/root/var/
    networks:
      - yugaplus-network
    cap_add:
      - NET_ADMIN

  yugabyte3:
    image: ytooyama/yugabyte-dev-tc:latest
    command: sh -c "sleep 12 && bin/yugabyted start --advertise_address=yugabyte3 --background=false --join=yugabyte1"
    ports:
      - "5435:5433"
    volumes:
      - yugabyte3-vol:/root/var/
    networks:
      - yugaplus-network
    cap_add:
      - NET_ADMIN

volumes:
  yugabyte1-vol:
  yugabyte2-vol:
  yugabyte3-vol:
  sysbench-vol:

networks:
  yugaplus-network:
    external: true